version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "rust"
    cooldown:
      default-days: 5
      semver-major-days: 10
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
    cooldown:
      default-days: 5
      semver-major-days: 10
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions:
        patterns:
          - "*"
