[package]
name = "cf_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.217"
serde_json = "1.0.137"
http = "1.2.0"
reqwest = { version = "0.12.12", default-features = false, features = ["json", "multipart",  "rustls-tls"] }
